Repository cloud-native-toolkit/image-github-terraform-runner, pull requests merged in 2022-08, with the labels that each got.

#1 Adds initial logic for runner
  .github/release-drafter.yaml
  .github/workflows/docker-build.yaml
  .github/workflows/release.yaml
  Containerfile
  README.md
  entrypoint.sh
  get-runner-release.sh
  get_github_app_token.sh
  register.sh
  uid.sh
Labels: feature, minor

#2 Regenerates with latest versions
  Containerfile
Labels: feature, minor

#3 Updates the readme
  README.md
Labels: chore, patch

#4 Pins version of base modules to specific versions
  .github/workflows/docker-build.yaml
  .github/workflows/update-base-image.yaml
Labels: chore, patch

#5 Adds logging to update-base-image workflow
  .github/workflows/update-base-image.yaml
Labels: chore, patch

#6 Fixes regex for update-base-image
  .github/workflows/update-base-image.yaml
Labels: chore, patch

#7 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.4.6
  .github/workflows/docker-build.yaml
Labels: bug, patch

#8 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.3
  .github/workflows/docker-build.yaml
Labels: bug, patch

#9 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.4.7
  .github/workflows/docker-build.yaml
Labels: bug, patch

#10 Updates cloud-native-toolkit/image-cli-tools module to v2.2.3
  .github/workflows/docker-build.yaml
Labels: bug, patch

#11 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.4
  .github/workflows/docker-build.yaml
Labels: bug, patch

#12 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.4.8
  .github/workflows/docker-build.yaml
Labels: bug, patch

#13 Updates cloud-native-toolkit/image-cli-tools module to v2.2.4
  .github/workflows/docker-build.yaml
Labels: bug, patch

#14 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.5
  .github/workflows/docker-build.yaml
Labels: bug, patch

#16 Updates cloud-native-toolkit/image-cli-tools module to v2.2.5
  .github/workflows/docker-build.yaml
Labels: bug, patch

#17 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.6
  .github/workflows/docker-build.yaml
Labels: bug, patch

#15 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.4.10
  .github/workflows/docker-build.yaml
Labels: bug, patch
