Repository cloud-native-toolkit/image-github-terraform-runner, pull requests merged in 2025-03, with the labels that each got.

#59 Updates cloud-native-toolkit/image-cli-tools-core module to v2.0.0
  .github/workflows/docker-build.yaml
Labels: feature, minor

#60 Updates cloud-native-toolkit/image-cli-tools-core module to v2.0.1
  .github/workflows/docker-build.yaml
Labels: bug, patch

#61 Updates cloud-native-toolkit/image-cli-tools module to v3.0.0
  .github/workflows/docker-build.yaml
Labels: feature, minor

#63 Updates cloud-native-toolkit/image-cli-tools module to v3.0.1
  .github/workflows/docker-build.yaml
Labels: bug, patch

#64 Updates cloud-native-toolkit/image-cli-tools module to v3.0.2
  .github/workflows/docker-build.yaml
Labels: bug, patch

#66 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.8.3
  .github/workflows/docker-build.yaml
Labels: bug, patch

#65 Update workflow configuration
  .github/workflows/docker-build.yaml
  Containerfile
Labels: chore, patch

#67 Updates cloud-native-toolkit/image-cli-tools-core module to v2.0.3
  .github/workflows/docker-build.yaml
Labels: bug, patch

#68 Updates cloud-native-toolkit/image-cli-tools-ibmcloud module to v0.8.4
  .github/workflows/docker-build.yaml
Labels: bug, patch

#69 Updates cloud-native-toolkit/image-cli-tools module to v3.0.3
  .github/workflows/docker-build.yaml
Labels: bug, patch
